account/urls.py
from django.urls import path

from .views import LoginView, RegisterView, ConfirmRegistrationView, Logout

app_name = 'account'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', ConfirmRegistrationView.as_view(), name='activate'),
    path('logout/', Logout.as_view(), name="logout")

]

blog/urls.py
from django.urls import path

from .views import IndexView, DetailView, BlogPostView, edit_blog_view, DeleteView


app_name = 'blog'
urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    path('detail/<slug:slug>/', DetailView.as_view(), name='detail'),
    path('create/', BlogPostView.as_view(), name="create"),
    path('edit/<slug>', edit_blog_view, name="edit"),
    path('delete/<int:pk>', DeleteView.as_view(), name="delete"),
]

fullfeaturedblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

home/templates/snippets/footer.html
<footer class="d-flex flex-row altign-iems-center bg-white shadow-lg">
    <p class="m-auto">Django Blog Application &copy 2020</p>
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

home/templates/snippets/header.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <nav>
        <a href="{% url 'home' %}" class="p-3 text-dark">Home</a>
        <a href="{% url 'blog:index' %}" class="p-3 text-dark">Blog</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'blog:create' %}" class="p-3 text-dark">Create Post</a>
            <a href="{% url 'account:logout' %}" class="p-3 text-dark">Logout</a>
            You are logged in as {{ request.user }}
            <img class="profile-picture small" src="{{ request.user.image.url }}">
        {% else %}
            <a href="{% url 'account:login' %}" class="p-3 text-dark">Login</a>
            <a href="{% url 'account:register' %}" class="p-3 text-dark">Register</a>
        {% endif %}
    </nav>
</div>